#ifndef OPENBATTLECORE_GLOBAL_H
#define OPENBATTLECORE_GLOBAL_H

#if QT
#include <QtCore/qglobal.h>

#if defined(OPENBATTLECORE_LIBRARY)
#  define OPENBATTLECORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define OPENBATTLECORESHARED_EXPORT Q_DECL_IMPORT
#endif
#else
#define OPENBATTLECORESHARED_EXPORT
#endif

#endif // OPENBATTLECORE_GLOBAL_H
